###
GET http://hakhi.xyz:8000/products

###
GET http://hakhi.xyz:8000/products?category=${id}


###
GET http://hakhi.xyz:8000/products?store=${id}

###
GET http://hakhi.xyz:8000/reviews?product=${id}
###
GET http://hakhi.xyz:8000/reviews?stars=4

###
GET http://localhost:8000/products?name=first

###
GET http://hakhi.xyz:8000/carts?customer=62
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYzNDAwMDU2MywiZXhwIjoxNjM2NTkyNTYzfQ.8gIVUDLGwT2MQEKKvnk1K41bPb_7_RsMurM7jKQU_Qs

###
PUT http://hakhi.xyz:8000/carts/81
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYzNDAwMDU2MywiZXhwIjoxNjM2NTkyNTYzfQ.8gIVUDLGwT2MQEKKvnk1K41bPb_7_RsMurM7jKQU_Qs
Content-Type: application/json

{
    "total_price": 2.99,
    "transaction": "pm_1JsdAlAKNmSLq2ZCAYTXyRx1"
}
###
GET http://hakhi.xyz:8000/stores?customer=6
###
GET http://localhost:8000/products?category=1

###
GET http://hakhi.xyz:8000/customers?user=13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYzNDAwMDU2MywiZXhwIjoxNjM2NTkyNTYzfQ.8gIVUDLGwT2MQEKKvnk1K41bPb_7_RsMurM7jKQU_Qs

###
PUT http://hakhi.xyz:8000/carts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYzNDAwMDU2MywiZXhwIjoxNjM2NTkyNTYzfQ.8gIVUDLGwT2MQEKKvnk1K41bPb_7_RsMurM7jKQU_Qs
Content-Type: application/json

{
    "is_actual": 1
}

###
GET http://hakhi.xyz:8000/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYzNDAwMDU2MywiZXhwIjoxNjM2NTkyNTYzfQ.8gIVUDLGwT2MQEKKvnk1K41bPb_7_RsMurM7jKQU_Qs

###
PUT http://hakhi.xyz:8000/carts/27
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYzNDAwMDU2MywiZXhwIjoxNjM2NTkyNTYzfQ.8gIVUDLGwT2MQEKKvnk1K41bPb_7_RsMurM7jKQU_Qs
Content-Type: application/json

{
    "carts": 26
}
###
GET http://hakhi.xyz:8000/customers?user=46
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImlhdCI6MTYzNDAwMDU2MywiZXhwIjoxNjM2NTkyNTYzfQ.8gIVUDLGwT2MQEKKvnk1K41bPb_7_RsMurM7jKQU_Qs
