# Build react pj
FROM node:12-alpine AS build
WORKDIR /app
# COPY package.json ./
COPY . .
RUN yarn install
RUN yarn build

# Raise a nginx server
FROM nginx:1.19.0-alpine AS prod-stage
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]